# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('RV', 'REVIEW'), ('RL', 'RELEASE'), ('RJ', 'REJECT')], default='RV', max_length=10)),
                ('is_ontop', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('index_img', models.CharField(max_length=250)),
                ('release_time', models.DateTimeField()),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsCategory'),
        ),
    ]
