# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_ontop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='release_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
